### ISSUE TITLE
Trouble with RxODE

### ISSUE THREAD

**Issue by rbarillot** [tdeswaef/GrassBlue#3]
I can't manage to get RxODE library working.
First, it told me to update R as RxODE is only available for R 3.6>. I now have R 4.0 but I got the following error :
`Erreur : package or namespace load failed for ‘RxODE’:
 .onAttach a échoué dans attachNamespace() pour 'RxODE', détails :
  appel : !.rxWinRtoolsPath(retry = NA)
  erreur : type de l'argument incorrect`

**Comment by tdeswaef** [comment]
You will have to install rtools40 (https://cran.r-project.org/bin/windows/Rtools/) for using it with R version 4.0

**Comment by rbarillot** [comment]
Ty, it's working now but I had to add the path "C:\rtools40\usr\bin" in my env variables.
Maybe you should mention it in your readme (see #1)

**Comment by tdeswaef** [comment]
I added this in the readme
